version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
    depends_on:
      - app
    restart: always

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: always
